use_frameworks!

platform :ios, '9.0'

target 'YDImageBrowser_Example' do
  pod 'YDImageBrowser', :path => '../'
  pod 'YYWebImage'
  
  target 'YDImageBrowser_Tests' do
    inherit! :search_paths

    
  end
end
